<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aviaservice.Application\KSTECH.Application.csproj" />
    <ProjectReference Include="..\Aviaservice.Domain\KSTECH.Domain.csproj" />
    <ProjectReference Include="..\Aviaservice.Infrastructure\KSTECH.Infrastructure.csproj" />
  </ItemGroup>

</Project>
