// <auto-generated />
using System;
using KSTECH.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KSTECH.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260523082042_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KSTECH.Domain.Modules.Issue", b =>
                {
                    b.Property<Guid>("id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<Guid?>("module_id")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<Guid?>("parent_id")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.HasKey("id")
                        .HasName("pk_issues");

                    b.HasIndex("module_id")
                        .HasDatabaseName("ix_issues_module_id");

                    b.HasIndex("parent_id")
                        .HasDatabaseName("ix_issues_parent_id");

                    b.ToTable("Issues", (string)null);
                });

            modelBuilder.Entity("KSTECH.Domain.Modules.Module", b =>
                {
                    b.Property<Guid>("id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("id")
                        .HasName("pk_modules");

                    b.ToTable("modules", (string)null);
                });

            modelBuilder.Entity("KSTECH.Domain.Modules.Issue", b =>
                {
                    b.HasOne("KSTECH.Domain.Modules.Module", null)
                        .WithMany("Issues")
                        .HasForeignKey("module_id")
                        .HasConstraintName("fk_issues_modules_module_id");

                    b.HasOne("KSTECH.Domain.Modules.Issue", "ParentIssue")
                        .WithMany("SubIssues")
                        .HasForeignKey("parent_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_issues_issues_parent_id");

                    b.OwnsOne("KSTECH.Domain.Modules.IssueDetails", "Details", b1 =>
                        {
                            b1.Property<Guid>("Issueid");

                            b1.HasKey("Issueid");

                            b1.ToTable("Issues");

                            b1
                                .ToJson("details")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("Issueid")
                                .HasConstraintName("fk_issues_issues_id");

                            b1.OwnsMany("KSTECH.Domain.Modules.File", "Files", b2 =>
                                {
                                    b2.Property<Guid>("IssueDetailsIssueid");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("PathToStorage")
                                        .IsRequired()
                                        .HasMaxLength(100);

                                    b2.HasKey("IssueDetailsIssueid", "__synthesizedOrdinal");

                                    b2.ToTable("Issues");

                                    b2.WithOwner()
                                        .HasForeignKey("IssueDetailsIssueid")
                                        .HasConstraintName("fk_issues_issues_issue_details_issueid");
                                });

                            b1.Navigation("Files");
                        });

                    b.Navigation("Details")
                        .IsRequired();

                    b.Navigation("ParentIssue");
                });

            modelBuilder.Entity("KSTECH.Domain.Modules.Issue", b =>
                {
                    b.Navigation("SubIssues");
                });

            modelBuilder.Entity("KSTECH.Domain.Modules.Module", b =>
                {
                    b.Navigation("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
